import mongoose from 'mongoose';

const userSchema = new mongoose.Schema(
  {
    clerkId:{
      type:String,
      required:true,
      unique:true
    },
    name: {
      type: String,
      required: true,
      trim: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      index: true,
    },
    gender: {
      type: String,
      enum: ['MALE', 'FEMALE', 'NON_BINARY', 'OTHER', 'PREFER_NOT_TO_SAY'],
      default: 'PREFER_NOT_TO_SAY',
    },
    college: {
      type: String,
      trim: true,
      default: '',
    },
    graduationDate: {
      type: Date, // ISO date string, e.g., "2027-06-01"
    },

    // Social & Portfolio Profiles
    githubUrl: {
      type: String,
      trim: true,
      default: '',
    },
    linkedinUrl: {
      type: String,
      trim: true,
      default: '',
    },

    // Cloud Storage Link to Uploaded Resume PDF (ImageKit)
    resumeFileUrl: {
      type: String,
      default: '',
    },

    // ---------------------------------------------------------
    // AI Pipeline Fields (Extracted via FastAPI & Gemini)
    // ---------------------------------------------------------
    
    // AI Vector generated from resume text (3072 dims for models/gemini-embedding-001)
    profileEmbedding: {
      type: [Number],
      default: undefined,
    },

    // Extracted experience tier used for pitch complexity scoring
    experienceLevel: {
      type: String,
      enum: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED'],
      default: 'INTERMEDIATE',
    },

    // Candidate profile overview generated by Gemini
    summary: {
      type: String,
      default: '',
    },

    // Flat array of primary & secondary skills for BM25 and stack overlap
    skills: {
      type: [String],
      default: [],
    },

    // Full structured JSON returned by LangChain (education, projects, certs)
    parsedProfile: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

export const User = mongoose.model('User', userSchema);