from typing import List, Optional
from pydantic import BaseModel, ConfigDict, Field
from app.schemas.hackathon import Hackathon


class PitchRequest(BaseModel):
    """
    Payload sent by Node.js to generate a tailored winning project strategy.
    """
    model_config = ConfigDict(populate_by_name=True)

    user_skills: List[str] = Field(
        default_factory=list,
        alias="userSkills",
        description="Technologies known by the candidate (e.g., ['React', 'Python', 'FastAPI'])"
    )
    user_experience: str = Field(
        default="INTERMEDIATE",
        alias="userExperience",
        description="Experience tier: 'BEGINNER', 'INTERMEDIATE', or 'ADVANCED'"
    )
    user_summary: Optional[str] = Field(
        default=None,
        alias="userSummary",
        description="Optional technical profile summary from resume to make pitch tailored to past work"
    )
    preferred_track: Optional[str] = Field(
        default=None,
        alias="preferredTrack",
        description="Optional specific hackathon theme/track if the competition has multiple tracks"
    )
    hackathon: Hackathon = Field(
        description="Full MongoDB Hackathon object containing title, techStack, and contextText"
    )


class HackathonPitch(BaseModel):
    """
    Structured project pitch generated by Gemini for a specific user and hackathon.
    """
    project_title: str = Field(
        description="Punchy, memorable project title tailored to the hackathon problem statement"
    )
    tagline: str = Field(
        description="A sharp 1-sentence hook explaining what the project does (e.g., 'An edge-AI drone pipeline that detects crop blight before symptoms show.')"
    )
    problem_statement: str = Field(
        description="2-sentence definition of the exact real-world pain point being addressed"
    )
    solution_overview: str = Field(
        description="3-4 sentence project overview bridging the candidate's skills to the hackathon themes"
    )
    key_features: List[str] = Field(
        description="3-4 core MVP features to build within a 24-36 hour hackathon window"
    )
    recommended_stack: List[str] = Field(
        description="Architecture stack combining user strengths and hackathon requirements"
    )
    teammate_recommendation: str = Field(
        description="Specific complementary profiles or missing technical skills to recruit for this project"
    )
    demo_strategy: str = Field(
        description="1-2 sentences on how to present an impactful live demo to judges (what to show first to win)"
    )